# Generated by Django 4.2.6 on 2023-10-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employer',
            table='employer',
        ),
    ]
