# Generated by Django 4.2.6 on 2023-10-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer_App', '0002_alter_employer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employer',
            table=None,
        ),
    ]
