# Generated by Django 4.2.6 on 2023-10-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NativeApp', '0004_alter_user_email_alter_user_password'),
        ('Employer_App', '0004_alter_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NativeApp.user'),
        ),
    ]
