# Generated by Django 4.2.6 on 2023-10-27 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hire_posting', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_hired', models.BooleanField(default=False)),
                ('cost', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NativeApp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.JSONField(default={'Friday': True, 'Monday': True, 'Saturday': True, 'Sunday': True, 'Thursday': True, 'Tuesday': True, 'Wednesday': True})),
                ('wage', models.IntegerField(null=True)),
                ('experience', models.IntegerField(null=True)),
                ('hiring_requests', models.ManyToManyField(related_name='workers', to='NativeApp.hiring')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('hiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NativeApp.hiring')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NativeApp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.typeofjobs')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NativeApp.worker')),
            ],
        ),
        migrations.AddField(
            model_name='hiring',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NativeApp.worker'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, upload_to='pics')),
                ('location', models.TextField(max_length=250)),
                ('user_type', models.CharField(choices=[('employer', 'employer'), ('worker', 'worker')], max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
