# Generated by Django 4.2.6 on 2023-10-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NativeApp', '0002_alter_customer_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='cust_user',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='user',
            new_name='cust_user',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='user',
            new_name='cust_user',
        ),
    ]
