# Generated by Django 4.2.6 on 2023-10-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NativeApp', '0003_rename_user_customer_cust_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='cust_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='cust_user',
            new_name='user',
        ),
    ]
