# Generated by Django 4.2.6 on 2023-10-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NativeApp', '0003_worker_job_types_delete_jobtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='messages',
        ),
    ]
