# Generated by Django 4.2.6 on 2023-11-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NativeApp', '0005_alter_worker_experience_alter_worker_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='experience',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wage',
            field=models.FloatField(null=True),
        ),
    ]
