# Generated by Django 4.2.6 on 2023-11-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NativeApp', '0008_remove_customer_city_remove_customer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
