# Generated by Django 4.2.6 on 2023-11-04 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NativeApp', '0010_alter_customer_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField()),
                ('hiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NativeApp.hiring')),
            ],
        ),
    ]
